### ISSUE TITLE
How to download artifacts

### ISSUE THREAD

**Issue by shaggygi** [SurveyMonkey/pyteamcity#20]
Is there any documentation that shows how to download artifact files using this module?  I came across the function get_build_artifacts_by_build_id, but not sure how to use.  Anything would be helpful (e.g. zip, txt, etc.).
Thanks

**Comment by msabramo** [comment]
I would recommend taking a look at [https://github.com/SurveyMonkey/pyteamcity/blob/master/pyteamcity/future/tests/unit/test_artifact.py](pyteamcity/blob/master/pyteamcity/future/tests/unit/test_artifact.py).

TL;DR:

```python
build = tc.builds.all().get(id=1216841)
file_artifact = build.artifacts / 'requirements.py27.lock'
assert file_artifact.size == 853
assert b'This is deploy_hooks/after_deploy' in file_artifact.content()
```
