### ISSUE TITLE
Documentation and samples still reference get_all_projects

### ISSUE THREAD

**Issue by curzona** [SurveyMonkey/pyteamcity#29]
`get_all_projects` was renamed to `_get_all_projects` and replaced with `get_projects` in b60e831.
[pyteamcity/sample.py](https://github.com/SurveyMonkey/pyteamcity/blob/b60e8313c71f0124a4e7d392f32b8c5667cb7031/sample.py) and [pyteamcity/README.md](https://github.com/SurveyMonkey/pyteamcity/blob/b60e8313c71f0124a4e7d392f32b8c5667cb7031/README.md) still mention `get_all_projects`.

**Comment by msabramo** [comment]
Thanks, @curzona!

**Comment by msabramo** [comment]
By the way, you may want to take a look at the new API in [`pyteamcity.future`](https://github.com/SurveyMonkey/pyteamcity/blob/master/pyteamcity/future). I think you'll find it easier to use, because there are a lot less method names and things are better organized.
