### ISSUE TITLE
Can't install from pypi

### ISSUE THREAD

**Issue by benbc** [SurveyMonkey/pyteamcity#76]
I've done a `pip install pyteamcity`, which appears to work, but then `import pyteamcity` fails (`ImportError: No module named pyteamcity`). Looking in my `site-packages`, I have a `dist-info` directory for `pyteamcity`, but no code directory.

Is it possible that the package on pypi is invalid in some way?

**Comment by zacharya19** [comment]
@msabramo The pypi package still not up to date.

**Comment by msabramo** [comment]
I just uploaded 0.1.1 to PyPI - https://pypi.python.org/pypi/pyteamcity/0.1.1

Thanks, @zacharya19!

Does that solve the problem?

**Comment by zacharya19** [comment]
Yes! great!

**Comment by msabramo** [comment]
Awesome! Thank you folks!
